version: '2.1'
services:
  seafile:
    image: rohwerj/seafile
    build:
      context: ./docker
    
    volumes:
      - seafile-vol:/seafile/data:rw

    environment:
      SERVER_DOMAIN: 127.0.0.1
      MYSQL_HOST: mysql
      MYSQL_USER: seafile
      MYSQL_PASS: seafile
      SEAFILE_ADMIN_EMAIL: test@test.de
      SEAFILE_ADMIN_PASSWORD: testit
      ENABLE_SEAFDAV: "true"

    depends_on: 
      - mysql
    
    container_name: seafile
    restart: unless-stopped

    dns:
      - ${IPV4_NETWORK:-172.22.1}.254
    ports:
      - 8000:8000
      - 8082:8082
      - 8080:8080
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=${SYSCTL_IPV6_DISABLED:-0}
    networks:
      seafile-network:
        aliases:
          - seafile


  mysql:
    image: mariadb:latest
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
      - mysql-vol:/var/lib/mysql/
    environment:
      - TZ=Europe/Berlin
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    restart: always
    dns:
      - ${IPV4_NETWORK:-172.22.1}.254
    ports:
      - "${SQL_PORT:-127.0.0.1:13306}:3306"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=${SYSCTL_IPV6_DISABLED:-0}
    networks:
      seafile-network:
        aliases:
          - mysql

networks:
  seafile-network:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: ${IPV4_NETWORK:-172.22.1}.0/24
        - subnet: ${IPV6_NETWORK:-fd4d:6169:6c63:6f77::/64}

volumes:
  seafile-vol:
  mysql-vol: