version: '2.1'
services:
  seafile:
    image: rohwerj/seafile
    build:
      context: ./docker
    
    volumes:
      - seafile-vol:/seafile/data:rw

    environment:
      SEAHUB:
      SEAFILE_FASTCGI_HOST: 0.0.0.0
      SERVER_DOMAIN: 127.0.0.1

    depends_on: 
      - mysql
    
    container_name: seafile
    restart: unless-stopped

    dns:
      - ${IPV4_NETWORK:-172.22.1}.254
    ports:
    ports:
      - 8000:8000
      - 8082:8082
      #Port 8080 is used for seafdav which is disabled by default
#      - 127.0.0.1:8080:8080
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=${SYSCTL_IPV6_DISABLED:-0}
    networks:
      seafile-network:
        aliases:
          - seafile


  mysql:
    image: mariadb:10.2
    volumes:
      - mysql-vol:/var/lib/mysql/
      - ./data/conf/mysql/:/etc/mysql/conf.d/:ro
    environment:
      - TZ=Europe/Berlin
      - MYSQL_ROOT_PASSWORD=LaE76DW3
      - MYSQL_DATABASE=seafile
      - MYSQL_USER=seafile
      - MYSQL_PASSWORD=seafile
    restart: always
    dns:
      - ${IPV4_NETWORK:-172.22.1}.254
    ports:
      - "${SQL_PORT:-127.0.0.1:13306}:3306"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=${SYSCTL_IPV6_DISABLED:-0}
    networks:
      seafile-network:
        aliases:
          - mysql

networks:
  seafile-network:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: ${IPV4_NETWORK:-172.22.1}.0/24
        - subnet: ${IPV6_NETWORK:-fd4d:6169:6c63:6f77::/64}

volumes:
  seafile-vol:
  seafile-vol-test:
  mysql-vol: